### PR TITLE
Add a license

### PR DESCRIPTION
**Pull request by madmuffin1**
All contributors need to accept this licensing before we can merge it, please add your vote by stating :+1:  or :-1: , if you conform or disagree with this change:

@TomTomaso , @sandro-k , @nime

### CODE REVIEW

**Comment by TomTomaso** [comment]
:+1:

**Comment by sandro-k** [comment]
:thumbsup:

**Comment by nime** [comment]
:thumbsup:

**Comment by madmuffin1** [comment]
:white_check_mark: Ready to be merged

**Pull request merged**
